spring:
  application:
    name: demo
  datasource:
    name: test
    url: jdbc:mysql://192.168.33.6:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxOpenPreparedStatements: 20
      #开启StatFilter
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        #开启Slf4jFilter
        slf4j:
          enabled: true
          data-source-log-enabled: false
          connection-log-enabled: false
          statement-log-enabled: false
          result-set-log-enabled: false
        #开启WallFilter
        wall:
          enabled: true
          log-violation: true
          throw-exception: false
          config:
            delete-where-none-check: true
      #开启Web监控
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
      #开启监控页面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
    dbcp2:
      min-idle: 5
      initial-size: 50
      max-total: 50
      max-wait-millis: 500
mybatis:
  type-aliases-package: com.example.demo.practice.model.pojo
  mapper-locations: classpath:mybatis/generator/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
logging:
  com.blog.springboot: WARN